// <auto-generated />
using System;
using ChamadosManutencao.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChamadosManutencao.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910004548_PermitirVariosAtendimentosPorChamado")]
    partial class PermitirVariosAtendimentosPorChamado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("seq_codigo_cliente");

            modelBuilder.HasSequence("seq_codigo_tecnico");

            modelBuilder.HasSequence("seq_numero_chamado");

            modelBuilder.HasSequence("seq_numero_fatura");

            modelBuilder.Entity("CategoriaServicoTecnico", b =>
                {
                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tecnico_id");

                    b.Property<Guid>("_especialidadesId")
                        .HasColumnType("uuid")
                        .HasColumnName("_especialidades_id");

                    b.HasKey("TecnicoId", "_especialidadesId")
                        .HasName("pk_tecnico_especialidade");

                    b.HasIndex("_especialidadesId")
                        .HasDatabaseName("ix_tecnico_especialidade__especialidades_id");

                    b.ToTable("tecnico_especialidade", (string)null);
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Atendimentos.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTimeOffset?>("DataHoraConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_conclusao");

                    b.Property<DateTimeOffset>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<Guid?>("GarantiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("garantia_id");

                    b.Property<string>("RelatoTecnico")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("relato_tecnico");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tecnico_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_atendimento");

                    b.HasIndex("ChamadoId")
                        .HasDatabaseName("ix_atendimento_chamado_id");

                    b.HasIndex("TecnicoId")
                        .HasDatabaseName("ix_atendimento_tecnico_id");

                    b.ToTable("atendimento", (string)null);
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Atendimentos.Garantia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("atendimento_id");

                    b.Property<DateTimeOffset>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTimeOffset>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<int>("PrazoDias")
                        .HasColumnType("integer")
                        .HasColumnName("prazo_dias");

                    b.HasKey("Id")
                        .HasName("pk_garantia");

                    b.HasIndex("AtendimentoId")
                        .IsUnique()
                        .HasDatabaseName("ix_garantia_atendimento_id");

                    b.HasIndex("DataFim")
                        .HasDatabaseName("ix_garantia_data_fim");

                    b.ToTable("garantia", null, t =>
                        {
                            t.HasCheckConstraint("ck_garantia_prazo", "prazo_dias > 0 AND data_fim > data_inicio");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Atendimentos.ItemOrcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("OrcamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("orcamento_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id")
                        .HasName("pk_item_orcamento");

                    b.HasIndex("OrcamentoId")
                        .HasDatabaseName("ix_item_orcamento_orcamento_id");

                    b.ToTable("item_orcamento", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_orcamento_quantidade", "quantidade > 0");

                            t.HasCheckConstraint("ck_item_orcamento_tipo", "tipo BETWEEN 1 AND 2");

                            t.HasCheckConstraint("ck_item_orcamento_valor", "valor_unitario >= 0");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Atendimentos.Orcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("atendimento_id");

                    b.Property<DateTimeOffset?>("DataHoraDecisao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_decisao");

                    b.Property<DateTimeOffset>("DataHoraRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_registro");

                    b.Property<DateTimeOffset>("PrazoAprovacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo_aprovacao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_orcamento");

                    b.HasIndex("AtendimentoId")
                        .HasDatabaseName("ix_orcamento_atendimento_id");

                    b.HasIndex("Status", "PrazoAprovacao")
                        .HasDatabaseName("ix_orcamento_status_prazo_aprovacao");

                    b.ToTable("orcamento", null, t =>
                        {
                            t.HasCheckConstraint("ck_orcamento_status", "status BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Avaliacoes.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comentario");

                    b.Property<DateTimeOffset>("DataHoraRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_registro");

                    b.Property<int>("Nota")
                        .HasColumnType("integer")
                        .HasColumnName("nota");

                    b.Property<Guid?>("TecnicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tecnico_id");

                    b.HasKey("Id")
                        .HasName("pk_avaliacao");

                    b.HasIndex("ChamadoId")
                        .IsUnique()
                        .HasDatabaseName("ix_avaliacao_chamado_id");

                    b.HasIndex("TecnicoId")
                        .HasDatabaseName("ix_avaliacao_tecnico_id");

                    b.ToTable("avaliacao", null, t =>
                        {
                            t.HasCheckConstraint("ck_avaliacao_nota", "nota BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Avaliacoes.RespostaAvaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("administrador_id");

                    b.Property<Guid>("AvaliacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("avaliacao_id");

                    b.Property<DateTimeOffset>("DataHoraResposta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_resposta");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("texto");

                    b.HasKey("Id")
                        .HasName("pk_resposta_avaliacao");

                    b.HasIndex("AvaliacaoId")
                        .IsUnique()
                        .HasDatabaseName("ix_resposta_avaliacao_avaliacao_id");

                    b.ToTable("resposta_avaliacao", (string)null);
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Catalogo.AreaAtendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bairro");

                    b.Property<string>("CepFinal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep_final");

                    b.Property<string>("CepInicial")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep_inicial");

                    b.Property<decimal>("TaxaDeslocamento")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("taxa_deslocamento");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tecnico_id");

                    b.HasKey("Id")
                        .HasName("pk_area_atendimento");

                    b.HasIndex("TecnicoId")
                        .HasDatabaseName("ix_area_atendimento_tecnico_id");

                    b.HasIndex("CepInicial", "CepFinal")
                        .HasDatabaseName("ix_area_atendimento_faixa_cep");

                    b.ToTable("area_atendimento", null, t =>
                        {
                            t.HasCheckConstraint("ck_area_atendimento_faixa_cep", "cep_inicial <= cep_final");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Catalogo.CategoriaServico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<bool>("CategoriaDeRisco")
                        .HasColumnType("boolean")
                        .HasColumnName("categoria_de_risco");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("descricao");

                    b.Property<bool>("ExigeFoto")
                        .HasColumnType("boolean")
                        .HasColumnName("exige_foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_categoria_servico");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_categoria_servico_nome");

                    b.ToTable("categoria_servico", (string)null);
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Catalogo.TipoServico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("CategoriaServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_servico_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tipo_servico");

                    b.HasIndex("CategoriaServicoId")
                        .HasDatabaseName("ix_tipo_servico_categoria_id");

                    b.ToTable("tipo_servico", (string)null);
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Chamados.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTimeOffset?>("DataHoraConfirmacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_confirmacao");

                    b.Property<DateTimeOffset>("DataHoraProposta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_proposta");

                    b.Property<int>("DuracaoEmMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_em_minutos");

                    b.Property<int>("OrigemProposta")
                        .HasColumnType("integer")
                        .HasColumnName("origem_proposta");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_agendamento");

                    b.HasIndex("ChamadoId")
                        .HasDatabaseName("ix_agendamento_chamado_id");

                    b.HasIndex("DataHoraProposta")
                        .HasDatabaseName("ix_agendamento_data_hora_proposta");

                    b.ToTable("agendamento", null, t =>
                        {
                            t.HasCheckConstraint("ck_agendamento_duracao", "duracao_em_minutos > 0");

                            t.HasCheckConstraint("ck_agendamento_origem", "origem_proposta BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_agendamento_status", "status BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Chamados.Anexo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caminho");

                    b.Property<Guid?>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTimeOffset>("DataHoraUpload")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_upload");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nome_arquivo");

                    b.Property<int>("Origem")
                        .HasColumnType("integer")
                        .HasColumnName("origem");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<Guid?>("TecnicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tecnico_id");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tipo_mime");

                    b.HasKey("Id")
                        .HasName("pk_anexo");

                    b.HasIndex("ChamadoId")
                        .HasDatabaseName("ix_anexo_chamado_id");

                    b.HasIndex("TecnicoId")
                        .HasDatabaseName("ix_anexo_tecnico_id");

                    b.ToTable("anexo", null, t =>
                        {
                            t.HasCheckConstraint("ck_anexo_dono_unico", "(chamado_id IS NOT NULL AND tecnico_id IS NULL) OR (chamado_id IS NULL AND tecnico_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_anexo_origem", "origem BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_anexo_tamanho", "tamanho_bytes > 0 AND tamanho_bytes <= 10485760");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Chamados.Chamado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ChamadoDeGarantia")
                        .HasColumnType("boolean")
                        .HasColumnName("chamado_de_garantia");

                    b.Property<Guid?>("ChamadoOriginalId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_original_id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("DataHoraAbertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_abertura");

                    b.Property<string>("DescricaoProblema")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao_problema");

                    b.Property<Guid?>("GarantiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("garantia_id");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TecnicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tecnico_id");

                    b.Property<Guid>("TipoServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_servico_id");

                    b.Property<int>("Urgencia")
                        .HasColumnType("integer")
                        .HasColumnName("urgencia");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_chamado");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_chamado_cliente_id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_chamado_numero");

                    b.HasIndex("TecnicoId")
                        .HasDatabaseName("ix_chamado_tecnico_id");

                    b.HasIndex("TipoServicoId")
                        .HasDatabaseName("ix_chamado_tipo_servico_id");

                    b.HasIndex("Status", "DataHoraAbertura")
                        .HasDatabaseName("ix_chamado_status_data_hora_abertura");

                    b.ToTable("chamado", null, t =>
                        {
                            t.HasCheckConstraint("ck_chamado_status", "status BETWEEN 1 AND 6");

                            t.HasCheckConstraint("ck_chamado_urgencia", "urgencia BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Chamados.HistoricoStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTimeOffset>("DataHoraAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_alteracao");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<int?>("StatusAnterior")
                        .HasColumnType("integer")
                        .HasColumnName("status_anterior");

                    b.Property<int>("StatusNovo")
                        .HasColumnType("integer")
                        .HasColumnName("status_novo");

                    b.Property<Guid>("UsuarioResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_responsavel_id");

                    b.HasKey("Id")
                        .HasName("pk_historico_status");

                    b.HasIndex("ChamadoId", "DataHoraAlteracao")
                        .HasDatabaseName("ix_historico_status_chamado_id_data_hora_alteracao");

                    b.ToTable("historico_status", null, t =>
                        {
                            t.HasCheckConstraint("ck_historico_status_valores", "status_novo BETWEEN 1 AND 6 AND (status_anterior IS NULL OR status_anterior BETWEEN 1 AND 6)");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Financeiro.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("atendimento_id");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTimeOffset>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxaDeslocamento")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("taxa_deslocamento");

                    b.Property<decimal>("ValorMaoObra")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor_mao_obra");

                    b.Property<decimal>("ValorPecas")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor_pecas");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor_total");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_fatura");

                    b.HasIndex("AtendimentoId")
                        .IsUnique()
                        .HasDatabaseName("ix_fatura_atendimento_id");

                    b.HasIndex("ChamadoId")
                        .HasDatabaseName("ix_fatura_chamado_id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_fatura_cliente_id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_fatura_numero");

                    b.HasIndex("Status", "DataVencimento")
                        .HasDatabaseName("ix_fatura_status_data_vencimento");

                    b.ToTable("fatura", null, t =>
                        {
                            t.HasCheckConstraint("ck_fatura_status", "status BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_fatura_valores", "valor_pecas >= 0 AND valor_mao_obra >= 0 AND taxa_deslocamento >= 0 AND valor_total >= 0");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Financeiro.FormaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("apelido");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<string>("tipo_forma_pagamento")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("tipo_forma_pagamento");

                    b.HasKey("Id")
                        .HasName("pk_forma_pagamento");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_forma_pagamento_cliente_id");

                    b.ToTable("forma_pagamento", (string)null);

                    b.HasDiscriminator<string>("tipo_forma_pagamento").HasValue("FormaPagamento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Financeiro.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DataHoraPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_pagamento");

                    b.Property<Guid>("FaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("fatura_id");

                    b.Property<Guid>("FormaPagamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("forma_pagamento_id");

                    b.Property<string>("IdentificadorTransacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identificador_transacao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id")
                        .HasName("pk_pagamento");

                    b.HasIndex("FaturaId")
                        .HasDatabaseName("ix_pagamento_fatura_id");

                    b.HasIndex("FormaPagamentoId")
                        .HasDatabaseName("ix_pagamento_forma_pagamento_id");

                    b.HasIndex("IdentificadorTransacao")
                        .HasDatabaseName("ix_pagamento_identificador_transacao");

                    b.ToTable("pagamento", null, t =>
                        {
                            t.HasCheckConstraint("ck_pagamento_status", "status BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_pagamento_valor", "valor_pago >= 0");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Pessoas.Imovel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("apelido");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cidade");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Complemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<int>("TipoImovel")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_imovel");

                    b.HasKey("Id")
                        .HasName("pk_imovel");

                    b.HasIndex("Cep")
                        .HasDatabaseName("ix_imovel_cep");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_imovel_cliente_id");

                    b.ToTable("imovel", null, t =>
                        {
                            t.HasCheckConstraint("ck_imovel_tipo", "tipo_imovel BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Pessoas.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("tipo_usuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_cpf_tecnico")
                        .HasFilter("tipo_usuario = 'Tecnico'");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_email_tecnico")
                        .HasFilter("tipo_usuario = 'Tecnico'");

                    b.ToTable("usuario", (string)null);

                    b.HasDiscriminator<string>("tipo_usuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ChamadosManutencao.Infrastructure.Auditoria.LogTransacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChavePrimaria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("chave_primaria");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entidade");

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("jsonb")
                        .HasColumnName("estado_anterior");

                    b.Property<string>("EstadoNovo")
                        .HasColumnType("jsonb")
                        .HasColumnName("estado_novo");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operacao");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_log_transacao");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("ix_log_transacao_data_hora");

                    b.HasIndex("Entidade", "ChavePrimaria")
                        .HasDatabaseName("ix_log_transacao_entidade_chave");

                    b.ToTable("log_transacao", (string)null);
                });

            modelBuilder.Entity("ChamadosManutencao.Infrastructure.Notificacao.NotificacaoEnviada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assunto");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("canal");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("corpo");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("destinatario_id");

                    b.Property<Guid>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("referencia_tipo");

                    b.HasKey("Id")
                        .HasName("pk_notificacao_enviada");

                    b.HasIndex("DestinatarioId")
                        .HasDatabaseName("ix_notificacao_enviada_destinatario_id");

                    b.HasIndex("ReferenciaTipo", "ReferenciaId")
                        .HasDatabaseName("ix_notificacao_enviada_referencia");

                    b.ToTable("notificacao_enviada", (string)null);
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Financeiro.Boleto", b =>
                {
                    b.HasBaseType("ChamadosManutencao.Domain.Financeiro.FormaPagamento");

                    b.Property<string>("EmailEnvio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email_envio");

                    b.Property<string>("NomeSacado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_sacado");

                    b.ToTable("forma_pagamento", (string)null);

                    b.HasDiscriminator().HasValue("Boleto");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Financeiro.CartaoCredito", b =>
                {
                    b.HasBaseType("ChamadosManutencao.Domain.Financeiro.FormaPagamento");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("bandeira");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_titular");

                    b.Property<string>("TokenOperadora")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token_operadora");

                    b.Property<string>("UltimosQuatroDigitos")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("ultimos_quatro_digitos");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("validade");

                    b.ToTable("forma_pagamento", (string)null);

                    b.HasDiscriminator().HasValue("CartaoCredito");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Financeiro.Pix", b =>
                {
                    b.HasBaseType("ChamadosManutencao.Domain.Financeiro.FormaPagamento");

                    b.Property<string>("ChavePix")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("chave_pix");

                    b.Property<int>("TipoChave")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_chave");

                    b.ToTable("forma_pagamento", (string)null);

                    b.HasDiscriminator().HasValue("Pix");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Pessoas.Administrador", b =>
                {
                    b.HasBaseType("ChamadosManutencao.Domain.Pessoas.Usuario");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matricula");

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_matricula")
                        .HasFilter("tipo_usuario = 'Administrador'");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Pessoas.Cliente", b =>
                {
                    b.HasBaseType("ChamadosManutencao.Domain.Pessoas.Usuario");

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_cliente");

                    b.HasIndex("CodigoCliente")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_codigo_cliente")
                        .HasFilter("tipo_usuario = 'Cliente'");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Pessoas.Tecnico", b =>
                {
                    b.HasBaseType("ChamadosManutencao.Domain.Pessoas.Usuario");

                    b.Property<string>("CodigoTecnico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_tecnico");

                    b.HasIndex("CodigoTecnico")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_codigo_tecnico")
                        .HasFilter("tipo_usuario = 'Tecnico'");

                    b.HasDiscriminator().HasValue("Tecnico");
                });

            modelBuilder.Entity("CategoriaServicoTecnico", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Pessoas.Tecnico", null)
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tecnico_especialidade_tecnicos_tecnico_id");

                    b.HasOne("ChamadosManutencao.Domain.Catalogo.CategoriaServico", null)
                        .WithMany()
                        .HasForeignKey("_especialidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tecnico_especialidade_categoria_servico__especialidades_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Atendimentos.ItemOrcamento", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Atendimentos.Orcamento", null)
                        .WithMany("_itens")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_orcamento_orcamento_orcamento_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Atendimentos.Orcamento", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Atendimentos.Atendimento", null)
                        .WithMany("_orcamentos")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orcamento_atendimento_atendimento_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Avaliacoes.RespostaAvaliacao", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Avaliacoes.Avaliacao", null)
                        .WithOne("Resposta")
                        .HasForeignKey("ChamadosManutencao.Domain.Avaliacoes.RespostaAvaliacao", "AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resposta_avaliacao_avaliacao_avaliacao_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Catalogo.AreaAtendimento", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Pessoas.Tecnico", null)
                        .WithMany("_areasAtendimento")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_area_atendimento_tecnicos_tecnico_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Catalogo.TipoServico", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Catalogo.CategoriaServico", null)
                        .WithMany("_tiposServico")
                        .HasForeignKey("CategoriaServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tipo_servico_categoria_servico_categoria_servico_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Chamados.Agendamento", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Chamados.Chamado", null)
                        .WithMany("_agendamentos")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agendamento_chamado_chamado_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Chamados.Anexo", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Chamados.Chamado", null)
                        .WithMany("_anexos")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_anexo_chamado_chamado_id");

                    b.HasOne("ChamadosManutencao.Domain.Pessoas.Tecnico", null)
                        .WithMany("_documentos")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_anexo_tecnicos_tecnico_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Chamados.HistoricoStatus", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Chamados.Chamado", null)
                        .WithMany("_historicoStatus")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historico_status_chamado_chamado_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Financeiro.FormaPagamento", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Pessoas.Cliente", null)
                        .WithMany("_formasPagamento")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forma_pagamento_clientes_cliente_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Financeiro.Pagamento", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Financeiro.Fatura", null)
                        .WithMany("_pagamentos")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagamento_fatura_fatura_id");

                    b.HasOne("ChamadosManutencao.Domain.Financeiro.FormaPagamento", null)
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagamento_forma_pagamento_forma_pagamento_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Pessoas.Imovel", b =>
                {
                    b.HasOne("ChamadosManutencao.Domain.Pessoas.Cliente", null)
                        .WithMany("_imoveis")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imovel_clientes_cliente_id");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Atendimentos.Atendimento", b =>
                {
                    b.Navigation("_orcamentos");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Atendimentos.Orcamento", b =>
                {
                    b.Navigation("_itens");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Avaliacoes.Avaliacao", b =>
                {
                    b.Navigation("Resposta");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Catalogo.CategoriaServico", b =>
                {
                    b.Navigation("_tiposServico");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Chamados.Chamado", b =>
                {
                    b.Navigation("_agendamentos");

                    b.Navigation("_anexos");

                    b.Navigation("_historicoStatus");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Financeiro.Fatura", b =>
                {
                    b.Navigation("_pagamentos");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Pessoas.Cliente", b =>
                {
                    b.Navigation("_formasPagamento");

                    b.Navigation("_imoveis");
                });

            modelBuilder.Entity("ChamadosManutencao.Domain.Pessoas.Tecnico", b =>
                {
                    b.Navigation("_areasAtendimento");

                    b.Navigation("_documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
